### ISSUE TITLE
Cant connect to WiFi/MQTT

### ISSUE THREAD

**Issue by MeisterQ** [Floyddotnet/esp32_mqtt_eq3#1]
Hello,

as we spoke at softypits Issues, here my Serial stuff:

https://pastebin.com/rUXL9U9a here my serial output.

it found my 2 devices, told me its connected to my Network but if i ping the ESP at 192.168.2.124 its says its not reachable.

(I didnt reset the ESP and enterd all infos at the beginning. Seems like its taking all infos it needs from EEProm)

**Comment by inforsgit** [comment]
I had exactly the same issue with exactly the same error! Took some head-scratching but it seems to be that it doesn’t accept a raw IP address for the MQTT server like the softypit version of the code (where I also had “192.168.2.173”...using your MQTT server address)

The error that lead me to it was:

 MQTT_CLIENT: Error parse uri = 192.168.2.173

For this version of the code you need to give the MQTT server address fully as:

mqtt://192.168.2.173

Then it should work!

Perhaps some more guidance on this could be added in the log?

**Comment by MeisterQ** [comment]
> 
> 
> I had exactly the same issue with exactly the same error! Took some head-scratching but it seems to be that it doesn’t accept a raw IP address for the MQTT server like the original version of the code (where I also had “192.168.2.173”...using your MQTT server address)
> 
> The error that lead me to it was:
> 
> MQTT_CLIENT: Error parse uri = 192.168.2.173
> 
> For this version of the code you need to give the MQTT server address fully as:
> 
> mqtt://192.168.2.173
> 
> Then it should work!
> 
> Perhaps some more guidance on this could be added in the log?

Hey,

entering only "mqtt://" infront of the ip-adress of MQTT server?

**Comment by inforsgit** [comment]
Exactly, that’s all you need to do when you’re setting up the eq3 bridge

**Comment by MeisterQ** [comment]
> 
> 
> Exactly, that’s all you need to do

But i cant even Ping my ESP

**Comment by MeisterQ** [comment]
> 
> 
> Exactly, that’s all you need to do when you’re setting up the eq3 bridge

Oh really. Its working. Wow. Thanks

**Comment by inforsgit** [comment]
Yeah, I had the same...sorry, should have said. The problem is it goes into a boot loop with this issue (which I also don’t think should be the case) so it’s hard to get into it. 

I ended up erasing the flash (because otherwise it will remember the mqtt details) and then re-flashing the esp32_mqtt_eq3 Software

**Comment by MeisterQ** [comment]
> 
> 
> Yeah, I had the same...sorry, should have said. The problem is it goes into a boot loop with this issue (which I also don’t think should be the case) so it’s hard to get into it.
> 
> I ended up erasing the flash (because otherwise it will remember the mqtt details) and then re-flashing the esp32_mqtt_eq3 Software

Thanks very much. Its working fine now.

Maybe this "mqtt://" line should be addet automatically by code to ip adress. Or it should be an additional information

**Comment by Floyddotnet** [comment]
> For this version of the code you need to give the MQTT server address fully as:
>
> mqtt://192.168.2.173
>
> Then it should work!

@inforsgit yes this is right .. this is the default behavior of the new MQTT API in the ESP SDK. this i overlook. Thanks for your research.

> Maybe this "mqtt://" line should be addet automatically by code to ip adress. Or it should be an additional information

I will fix this soon. sorry. i overlook this change

**Comment by MeisterQ** [comment]
So my suggestion:

Adding "mqtt://" infront of our entered IP by code.

Also, if entering ESPs IP on browser when connected to the network, we should have the ability to enter the webpage again to do some changes

**Comment by MeisterQ** [comment]
Also: Im always getting response with "TRV not available"  when i send 2 commands for 2 devices.

One device is working, one says not available
